Remove `___store` from URL when configured
elgentos/magento2-alternate-urls pull request #3
Opened 2022-02-03 08:57 UTC by ArjenMiedema

When redirecting between websites, the `___store` parameter is
automatically added to the URL by Magento. This can now be removed when
configured this way.

2022-02-03 10:53 UTC, janmartendeboer requested changes

2022-02-03 10:53 UTC, janmartenjongerius commented on src/Type/AbstractType.php
> +        return explode($url, '?', 2)[0] ?? $url;
If you really only want to remove the store param, this can be solved in multiple ways. Can we discuss in person how fair it is that we now omit all other parameters?

2022-02-03 10:53 UTC, janmartendeboer commented on src/Type/Product.php
> +        if (!in_array($websiteId, $currentProduct->getWebsiteIds() ?? [])) {
Please use the `strict` flag to prevent type juggling.

2022-02-03 10:53 UTC, janmartendeboer commented on src/Type/Product.php
> +            return null;
You can reduce the return points and make it the last code point in the method, by putting the return value in a variable.

```php
$result = null;

if (in_array($websiteId, $currentProduct->getWebsiteIds() ?? [], true)) {
    try {
        $result = ...
    } catch (NoSuchEntityException $e) {
        $result = null;
    }
}

return $result;
```

2022-02-03 11:06 UTC, ArjenMiedema commented on src/Type/AbstractType.php
> +        return explode($url, '?', 2)[0] ?? $url;
In the end we don't want to have the parameters in here at all, as we need the plain URL.

2023-05-23 07:07 UTC, janmartenjongerius approved these changes

2023-05-23 08:15 UTC, merged